package com.example.ecommerceapp.data.model;

public class OrderItem {
    private String orderItemId; // Could be same as product ID if 1 product per order item, or unique
    private String productId;
    private String productName; // Denormalized for easier display in order history
    private int quantity;
    private double pricePerUnit; // Price at the time of order
    private double subtotal;

    public OrderItem(String orderItemId, String productId, String productName, int quantity, double pricePerUnit) {
        this.orderItemId = orderItemId;
        this.productId = productId;
        this.productName = productName;
        this.quantity = quantity;
        this.pricePerUnit = pricePerUnit;
        this.subtotal = quantity * pricePerUnit;
    }

    // Constructor from CartItem
    public OrderItem(CartItem cartItem) {
        this.productId = cartItem.getProduct().getProductId();
        this.productName = cartItem.getProduct().getName(); // Denormalize name
        this.quantity = cartItem.getQuantity();
        this.pricePerUnit = cartItem.getProduct().getPrice(); // Price at time of adding to cart (or checkout)
        this.subtotal = cartItem.getSubtotal();
        // orderItemId might be generated by the backend or be same as productId for simplicity here
        this.orderItemId = "item_" + this.productId + "_" + System.nanoTime(); // Simple unique ID
    }


    // Getters
    public String getOrderItemId() { return orderItemId; }
    public String getProductId() { return productId; }
    public String getProductName() { return productName; }
    public int getQuantity() { return quantity; }
    public double getPricePerUnit() { return pricePerUnit; }
    public double getSubtotal() { return subtotal; }

    // Setters if needed, but usually OrderItems are immutable once created for an order
}
